### PR TITLE
Added swift template definition

### PR DESCRIPTION
**Pull request by lorenalexm**
This pull request is to add a Swift with Swift Package Manager support to the store.

- https://github.com/lorenalexm/swift-template-openfaas

Signed-off-by: Alex Loren <lorenalexm@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @lorenalexm, I'm interested in having this merged into the store.

I need a couple of things though:

* change the Dockerfile to use a non-root user
* `swift:latest` - please change this to a specific pinned version
* combine all the `RUN` steps with `&& \` so that caching can take place

Other than that, looking forward to having this addition.

Alex

**Comment by alexellis** [comment]
I see you need to rebase the commit, please can you squash that down into just one commit? I don't want to take a "merge commit" into the master when it's not required.

If you need any help with that, our contribution guide may help - there's also plenty on Google - or we can help on Slack in #templates

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by lorenalexm** [comment]
Thank you for the feedback @alexellis

I have a bit of a busy weekend, but I will delve into these issues in the coming days!

**Comment by alexellis** [comment]
This looks good now, please rebase the file, don't do a merge commit.

i.e.
```
git fetch origin
git rebase origin/master
```

**Pull request closed without merging**
