### PR TITLE
OpenFaaS function for Caire content aware image resize library.

### PR DESCRIPTION
**Pull request by esimov**
Signed-off-by: esimov

### CODE REVIEW

**Comment by alexellis** [comment]
I think this will be a good addition. We just need some way to help the users to understand how to use the function once it's deployed in the UI.

**Comment by esimov** [comment]
Great, let me know if i have to adapt in some way the current implementation.

**Comment by alexellis** [comment]
Derek add label: blocked

**Comment by alexellis** [comment]
https://github.com/openfaas/store/pull/41#issuecomment-423164950

This is a great function - our UI just can't support the rich set of user-input/data that is required. An issue has been opened in openfaas/faas, but nobody has worked on it.

https://github.com/openfaas/faas/issues/890

**Comment by CrystalMethod** [comment]
@alexellis what do you think about including an optional form based on json schema? of course the question remains how to register the json schema which belongs to a function in the gateway.

**Comment by alexellis** [comment]
Having a clear-up on GitHub issues / PRs over 1 month old. Let's revisit as necessary. Thank you for the PR.

**Pull request closed without merging**
