### PR TITLE
Remove Network attribute for x86 and armhf

### LINKED ISSUE #27: Remove network attributes from store.json & store-armhf.json files
With the changes implemented in https://github.com/openfaas/faas-swarm/commit/e36f90b36f5b81498ea7dc018b3cf0b48127f7a1 the network attribute can be ascertained by the swarm backend.

This issue is to remove the network values from the store.json & store-armhf.json files

### PR DESCRIPTION
**Pull request by rgee0**
Fixes #27 

Removing the value and then the whole attribute have both been tested.  Both appeared to behave in the same fashion,  so with brevity in mind I opted for removing the whole attribute over an empty one.

Tested the deployment through both the UI and the CLI (by using the `-u` facility)

**This is a breaking change for anyone not running gateway:0.7.6 or greater**

The response returned from gateway:0.7.0 is:

Unexpected status: 400, message: Deployment error: Error response from daemon: network  is ambiguous (4 matches found)

Signed-off-by: rgee0 <richard@technologee.co.uk>

### CODE REVIEW

**Comment by alexellis** [comment]
@rgee0 I think this has been covered in master?

**Comment by alexellis** [comment]
I wasn't sure from the diff window if this was needed, but it looks like this to go ahead but in a new or rebased PR.

**Comment by rgee0** [comment]
Rebased and cleaned up - no conflicts

**Comment by ivanayov** [comment]
@rgee0 can you please rebase?

**Pull request merged**
