### PR TITLE
Update youtube-dl to working multiarch and auto updating container

### PR DESCRIPTION
**Pull request by hijak**
Update youtube-dl to working multiarch and auto updating container

youtube-dl is constantly updated to keep up with youtube api changes. I have taken this into account and set a weekly timer in the container to update the module. the current container does not work out the box, i have also added arm64 as thats is looking a bit sparse

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for your interesting. I'm really not keen on having CRON installed in the container and having itself update, this also implies a writeable filesystem and root access which is not the case on all deployments.

What problem are we trying to solve here? Maybe @rgee0 or the project can help?

**Comment by hijak** [comment]
Hi Alex

The youtube-dl container does not work out the box, the pip package is too old
This or regular builds would fix this issue

**Comment by rgee0** [comment]
I've fixed the existing images - thanks for highlighting.

Whether Alex wants to merge this is a matter for @hijak and @alexellis.  A couple of points to note, though:

1) Since this is a community function the source repo should remain as https://github.com/faas-and-furious/youtube-dl with any changes being merged across there first.

2) The questions Alex asked initially were a result of there not being an associated issue.  I recommend reviewing https://github.com/openfaas/store#make-a-submission-to-the-function-store and consequently following the [CONTRIBUTION guide](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md)

Thanks

**Comment by hijak** [comment]
hey sure no problem as long as you are aware of the issue

**Pull request closed without merging**
