### PR TITLE
Add LSB Steganography function

### LINKED ISSUE #79: Submission Request, LSB Steganography function
I created a steganography function that can be usefull for some, and fun for others. Hope you find it interesting. It has 100% test coverage and CircleCi integration in my repo.

```json
{
    "title": "LSB Steganography",
    "description": "LSB steganography encoding/decoding on base64 images",
    "images": {
        "x86_64": "auyer/fn-steganography"
    },
    "name": "steganography",
    "repo_url": "https://github.com/auyer/fn-steganography",
    "labels": {
        "com.openfaas.ui.ext": "json"
    }
}
```

### PR DESCRIPTION
**Pull request by auyer**
This function is capable of Encoding and Decoding using LSB Steganography

Fixes #79

Signed-off-by: Rafael Passos <rafael@rcpassos.me>

### CODE REVIEW

**Comment by alexellis** [comment]
I think I understand the function now, but I don't think the user journey is good enough in the Portal to merge this right now.

There are several other functions with complex inputs beyond a URL where the experience is poor.

We need a help text to be displayed in the UI, at the very least a link out to the originating repo's README. cc @burtonr

**Comment by auyer** [comment]
I agree. I plan to get some more work done to this function, in the future ( I'm unavailable atm).  

Besides changing the function, I see two ways that the Portal could be improved to make complex functions more available:
- Set a "request template" in the portal. This could be configured in the `yaml`, and show up when the input box is empty or with a button.
-  A tool to upload and encode files into a json for image-related functions.

Shall we discuss this in Slack ?

**Comment by alexellis** [comment]
Having a clear-up on GitHub issues / PRs over 1 month old. Let's revisit as necessary. Thank you for the PR.

**Comment by auyer** [comment]
Hi @alexellis , I just re-visited this function. 
What I did: 

- re-tested everything ( including from the UI),
- improved the support for URLs,
- did some minor improvements to the code and docs,
- a few usability improvements,
- migrated from `dep` to `go.mod` (still vendoring the only lib used)

Its working fine, and its usable once the user reads the quite simple README.md (witch is necessary to use most functions anyway)
Since this function deals with files, using it in the web UI is not the best experience, but it works. Most people will use it from code or from a terminal.

**Comment by LucasRoesler** [comment]
@auyer the latest master of your function is not passing CI, perhaps we want to get that fixed first
image

**Comment by auyer** [comment]
> @auyer the latest master of your function is not passing CI, perhaps we want to get that fixed first
> image

Geez I changed the job name and forgot to change it in the workflow.

**Pull request closed without merging**
