### PR TITLE
Migrate from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by nitishkumar71**
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>

Description

We want to migrate from Travis CI to Github Actions
Fixes openfaas/faas#1585
How Has This Been Tested?

Please check [CI Only](https://github.com/nitishkumar71/store/actions/runs/402102300) Build

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, I've checked the PR and I don't think this is right, it says the testing of the images took 16s - it should be much longer. Can you compare it to the Travis build?

Please can you look into it?

**Comment by nitishkumar71** [comment]
Sure, I will look into it.

**Comment by nitishkumar71** [comment]
@alexellis So just looked into it. So the entire travis build takes 40 seconds, but the script execution takes around 16-20 seconds.

just checked the time taken to execute each step in job log of few of previous pull request

https://travis-ci.com/github/openfaas/store/builds/147624170
https://travis-ci.com/github/openfaas/store/builds/147624170
https://travis-ci.com/github/openfaas/store/builds/159423705

Even entire Gitlab CI completion takes more than 40 seconds, but the job only takes around 16-20 seconds
https://github.com/nitishkumar71/store/actions/runs/402102300
https://github.com/nitishkumar71/store/actions/runs/402090422

**Comment by alexellis** [comment]
@nitishkumar71 thanks for confirming. I'll get this merged then.

Can you confirm if the build passes in master?

**Comment by nitishkumar71** [comment]
> @nitishkumar71 thanks for confirming. I'll get this merged then.
> 
> Can you confirm if the build passes in master?

@alexellis the [build](https://github.com/openfaas/store/actions/runs/501081257) passed in master.

**Pull request merged**
