### PR TITLE
adds openfaas-exif

### PR DESCRIPTION
**Pull request by scottleedavis**
Associated with Issue #100

### CODE REVIEW

**Comment by scottleedavis** [comment]
Apologies, I am not used to signed off commits and doing a mess of time here.

**Comment by scottleedavis** [comment]
I have tried resolving the signoff issue as recommended, however the bot label is still here, and not sure what I need to do to resolve it.  Do I need to amend every commit in this PR?

**Comment by alexellis** [comment]
We have a conflict on `store.json`

Try?
```
git pull origin master --rebase

# fix conflicts

git add .
git rebase --continue
```

**Comment by scottleedavis** [comment]
updated

**Comment by scottleedavis** [comment]
Strange hold travis is green, but build is stuck on not completed yet.  https://travis-ci.org/openfaas/store/builds/604573410?utm_source=github_status&utm_medium=notification

**Comment by alexellis** [comment]
Hi, sorry but I asked you to do a rebase and we ended up with a merge, can you reset the commits and send a single one in please?

**Comment by scottleedavis** [comment]
Apologies, I assumed wrongly that a rebase wasn't required.

**Pull request closed without merging**
