### PR TITLE
Extend faas-store with coherent line drawing functions

### PR DESCRIPTION
**Pull request by esimov**
Signed-off-by: esimov <esimovaq@yahoo.com>

Extended the store with the Coherent Line Drawing function, for which i have opened the following ticket: https://github.com/openfaas/store/issues/90

### CODE REVIEW

**Comment by alexellis** [comment]
What's the example usage please?

**Comment by alexellis** [comment]
@esimov PTAL

**Comment by alexellis** [comment]
@esimov I looked at the repo. Please can you add on your repo an example of how someone could construct and example with query string parameters?

I know that we know this - but it's not obvious for every OpenFaaS user.

We have made some changes to the way that the store works, so you also need to modify `functions.json` for this to show up on newer clients.'

Thanks,

Alex

**Comment by esimov** [comment]
@alexellis i have already provided an example with query parameters and it is included into the documentation. Can you check it please? What else i need to modify?

**Comment by alexellis** [comment]
See my note about functions.json

**Comment by alexellis** [comment]
Hi @esimov 

Please could you check the two build failures after you sent your PR? Just click the links above where you see a red X.

Alex

**Comment by esimov** [comment]
@alexellis can you check it now please?

**Comment by alexellis** [comment]
From what I saw late on Sunday evening, the image you were using had not been published to the Docker Hub. Glad that @rgee0 put that validation in for us, it's coming in useful

Looks like you fixed the error.

Alex

**Comment by alexellis** [comment]
Thanks for your PR @esimov 👍

**Comment by esimov** [comment]
> From what I saw late on Sunday evening, the image you were using had not been published to the Docker Hub. Glad that @rgee0 put that validation in for us, it's coming in useful
> 
> Looks like you fixed the error.
> 
> Alex

Yes, that was the problem, that i forgot to publish to the Docker Hub.

**Pull request merged**
