### PR TITLE
Added F# template to templates.json

### PR DESCRIPTION
**Pull request by hayer**
Added my F# template to the templates.json list, #64.

### CODE REVIEW

**Comment by hayer** [comment]
@alexellis think I got the sign-off right. Checks passed. Merge OK?

**Comment by alexellis** [comment]
Please reset the commits and apply a single commit, thanks.

**Comment by hayer** [comment]
@alexellis all done?

**Comment by alexellis** [comment]
Screenshot 2019-06-04 at 19 32 56

`git` can be tricky at times. Perhaps it would be easier for you to raise a new PR and close this one?

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by hayer** [comment]
Yea, sorry. Was in a hurry, went a little to fast there.

**Pull request closed without merging**
