### PR TITLE
Convert Json to MD in order to display directly in GitHub the store content

### PR DESCRIPTION
**Pull request by itscaro**
- Convert Json to MD in order to display directly in GitHub the store content
- Add CI to validate json files

Relates to #13

### CODE REVIEW

**Comment by alexellis** [comment]
How are you making sure the files get back into the Git repo?

**Comment by itscaro** [comment]
the idea is to have a command to be run by maintainer or CI after merging, the command generates MD files which will be committed either by the maintainer or directly by CI to the repo

**Comment by alexellis** [comment]
I like the generated markdown, but I am not sure that pushing that back to Git in CI is the right way to do it. We could probably publish this to GitHub pages instead.

**Comment by itscaro** [comment]
I thought about Github pages yesterday too, but still, CI or the maintainer need to commit the modified *.md to the repo. With Github using gh-pages branch, history of commits is separated, it is a good solution, IMO.

I created a test of gh pages here: https://itscaro.github.io/store/

**Comment by alexellis** [comment]
I think this is a good start, but I need to look into it when I have more time and see if we can publish to GitHub pages via a CI process.

**Comment by alexellis** [comment]
Having a clear-up on GitHub issues / PRs over 1 month old. Let's revisit as necessary. Thank you for the PR.

**Pull request closed without merging**
